#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/jenkins

# -------------------------
# Install Java
# -------------------------
- name: Install Java on Ubuntu
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Java on RHEL / Amazon
  dnf:
    name: java-17-openjdk
    state: present
  when: ansible_os_family == "RedHat"

# -------------------------
# Jenkins repo (Ubuntu)
# -------------------------
- name: Add Jenkins key (Ubuntu)
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
  when: ansible_os_family == "Debian"

- name: Add Jenkins repo (Ubuntu)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
  when: ansible_os_family == "Debian"

# -------------------------
# Jenkins repo (RHEL/Amazon)
# -------------------------
- name: Add Jenkins repo (RHEL/Amazon)
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  when: ansible_os_family == "RedHat"

- name: Import Jenkins key (RHEL/Amazon)
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    state: present
  when: ansible_os_family == "RedHat"

# -------------------------
# Install Jenkins
# -------------------------
- name: Install Jenkins (Ubuntu)
  apt:
    name: jenkins
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  notify: Restart Jenkins

- name: Install Jenkins (RHEL/Amazon)
  dnf:
    name: jenkins
    state: present
  when: ansible_os_family == "RedHat"
  notify: Restart Jenkins

# -------------------------
# Start Jenkins
# -------------------------
- name: Start Jenkins
  systemd_service:
    name: jenkins
    state: started
    enabled: yes
  become: true

# -------------------------
# Verify Jenkins version
# -------------------------
- name: Get Jenkins version
  ansible.builtin.command: java -jar /usr/lib/jenkins/jenkins.war --version
  register: jenkins_version
  changed_when: false

- name: Print Jenkins version
  ansible.builtin.debug:
    var: jenkins_version.stdout
