apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:selectorLabels
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.configmap_data.PORT }}
              protocol: TCP
          env:
            # Environment variables
            # from configmap
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: langchoice-backend-cm
                  key: DB_NAME

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: langchoice-backend-cm
                  key: PORT

            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: langchoice-backend-cm
                  key: ALLOWED_ORIGINS

            - name: VPC_CIDR
              valueFrom:
                configMapKeyRef:
                  name: langchoice-backend-cm
                  key: VPC_CIDR

            - name: MONGODB_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username

            - name: MONGODB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
              
            - name: MONGODB_URI
              value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@{{ .Release.Name }}-mongodb:27017/$(DB_NAME)?authSource=admin"

          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
