# ClusterSecretStore tell the external secret operator
# in cluster how to authenticate with aws to read from 
# secret manager
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
