apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: langchoice
spec:
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: mongodb-secret
        property: rootPassword

    - secretKey: mongodb-passwords
      remoteRef:
        key: mongodb-secret
        property: password

    - secretKey: mongodb-password
      remoteRef:
        key: mongodb-secret
        property: password
    
    - secretKey: mongodb-username
      remoteRef:
        key: mongodb-secret
        property: username

    - secretKey: mongodb-database
      remoteRef:
        key: mongodb-secret
        property: database