apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secret
spec:
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
  data:
    - secretKey: mongodb-username
      remoteRef:
        key: mongodb-secret
        property: username

    - secretKey: mongodb-password
      remoteRef:
        key: mongodb-secret
        property: password

    - secretKey: mongodb-root-password
      remoteRef:
        key: mongodb-secret
        property: rootPassword