apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
spec:
  target:
    name: mongodb-secret
  data:
    - secretKey: mongodb-username
      remoteRef:
        key: mongodb-secret
        property: username

    - secretKey: mongodb-password
      remoteRef:
        key: mongodb-secret
        property: password

    - secretKey: mongodb-root-password
      remoteRef:
        key: mongodb-secret
        property: rootPassword